---
- hosts: ubuntu
  become: yes
  tasks:

  - name: Install PHP and PHP-fpm
    apt:
      name: 
      - php
      - php-fpm
      update_cache: true
    notify:
      systemd

  handlers:
  - name: systemd
    systemd:
      name: php7.4-fpm
      enabled: false
      state: stopped
