---
- hosts: centos
  become: yes 
  tasks:
# - name: Add Zabix repo
#   ansible.builtin.shell:
#     cmd: rpm -Uvh https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-4.el7.noarch.rpm

  - name: Install PostreSQL-12 repo
    ansible.builtin.yum:
      name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      state: latest

  - name: Install PostgreSQL-12
    yum:
      name:
        - epel-release
        - postgresql12-server
        - postgresql12

          #- name: Initialize DB
          #command: /usr/pgsql-12/bin/postgresql-12-setup initdb

  - name: Restart PostgreSQL Server
    service:
      name: postgresql-12
      enabled: yes 
      state: restarted
