---
- hosts: centos
  become: yes 
  tasks:
          #- name: Add Zabix repo
          #ansible.builtin.shell:
          #cmd: rpm -Uvh https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-4.el7.noarch.rpm

  - name: Install Zabix agent
    ansible.builtin.yum:
      name: zabbix-agent
      state: latest
    notify:
      zabbix systemd

  - name: Configure Zabbix server
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      line: "{{ item.line }}"
      regexp: "{{ item.regexp }}"
    loop:
      - regexp: '^Server='
        line: 'Server=10.8.0.1'
      - regexp: '^ServerActive='
        line: 'ServerActive=10.8.0.1'
      - regexp: '^Hostname='
        line: 'Hostname={{ ansible_hostname }}'
  - name: Restart service
    ansible.builtin.service:
      name: zabbix-agent
      state: restarted

  handlers:
  - name: zabbix systemd
    systemd:
      name: zabbix-agent
      enabled: yes 
      state: started
